<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EG-AMOHAMMAD" ignored="0" name="Test1" tests="3" failures="1" timestamp="2020-07-15T18:03:59 EET" time="70.811" errors="0">
  <testcase name="testCalFun" time="32.441" classname="com.sample.tests.CalendarTests"/>
  <testcase name="testCalRemainder" time="20.03" classname="com.sample.tests.CalendarTests"/>
  <testcase name="testCountOfEvents" time="18.241" classname="com.sample.tests.CalendarTests">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at com.sample.tests.CalendarTests.testCountOfEvents(CalendarTests.java:36)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testCountOfEvents -->
</testsuite> <!-- Test1 -->
